version: '3.8'

services:
  payroll_php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: payroll_php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - payroll-network
    depends_on:
      - payroll_mysql

  payroll_nginx:
    image: nginx:1.19.10-alpine
    container_name: payroll_nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    networks:
      - payroll-network
    depends_on:
      - payroll_php

  payroll_mysql:
    image: mysql:8.0.20
    container_name: payroll_mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: payroll
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql:rw
      - ./docker/mysql-backups/:/mysql-backups/:rw
    ports:
      - '3306:3306'
    networks:
      - payroll-network

volumes:
  dbdata:

networks:
  payroll-network:
    driver: bridge
